SELECT
	AIRCRAFT.TAIL_NUMBER,
	MODEL.MODEL_NUMBER,
	MODEL.DESCRIPTION,
	COMPANIES.COMPANY_NAME,
	COUNTRY_CODES.CODE,
	COUNTRY_CODES.COUNTRY_NAME
FROM
	AIRCRAFT
INNER JOIN MODEL ON AIRCRAFT.MDL_AUTO_KEY = MODEL.MDL_AUTO_KEY
INNER JOIN COMPANIES ON AIRCRAFT.CMP_OWNER = COMPANIES.CMP_AUTO_KEY
INNER JOIN COUNTRY_CODES ON COMPANIES.COC_AUTO_KEY = COUNTRY_CODES.COC_AUTO_KEY
WHERE COUNTRY_CODES.SDF_COC_002 != 'Europe'
ORDER BY 
	COUNTRY_CODES.CODE, 
	COMPANIES.COMPANY_NAME,
	MODEL.DESCRIPTION;